datos = [
    "insert into TipoCliente (tipo) values ('Desconocido');",
    "insert into TipoCliente (tipo) values ('Distribuidor');",
    "insert into TipoCliente (tipo) values ('Usuario final');",
    "insert into TipoCliente (tipo) values ('Integrador');",
    "insert into TipoCliente (tipo) values ('Academia');",
    "insert into Mercado (nombre, codigo) values ('Academia', 'ACA');",
    "insert into Mercado (nombre, codigo) values ('Aeropuerto', 'AER')",
    "insert into Mercado (nombre, codigo) values ('Agronomía', 'AGR')",
    "insert into Mercado (nombre, codigo) values ('Cadena fría', 'CFR')",
    "insert into Mercado (nombre, codigo) values ('Colores', 'COL')",
    "insert into Mercado (nombre, codigo) values ('Cross Market', 'XMT')",
    "insert into Mercado (nombre, codigo) values ('Datacenter', 'DCS')",
    "insert into Mercado (nombre, codigo) values ('Desconocido', 'UNK')",
    "insert into Mercado (nombre, codigo) values ('Energía', 'ENE')",
    "insert into Mercado (nombre, codigo) values ('Farmacéutica', 'PHA')",
    "insert into Mercado (nombre, codigo) values ('Galerías-Museos-Bibliotecas', 'GMB')",
    "insert into Mercado (nombre, codigo) values ('Hidrología', 'HID')",
    "insert into Mercado (nombre, codigo) values ('HVAC', 'HVA')",
    "insert into Mercado (nombre, codigo) values ('Industria', 'IND')",
    "insert into Mercado (nombre, codigo) values ('Invernaderos', 'INV')",
    "insert into Mercado (nombre, codigo) values ('Medio ambiente', 'MAM')",
    "insert into Mercado (nombre, codigo) values ('Tratamiento de agua', 'H2O')",
    "insert into Mercado (nombre, codigo) values ('Residencial', 'RED')",
    "insert into Mercado (nombre, codigo) values ('Water monitoring', 'WMO')",
    "insert into Marca (nombre, codigo) values ('AccuEnergy', 'ACC')",
    "insert into Marca (nombre, codigo) values ('AccuTools', 'ACT')",
    "insert into Marca (nombre, codigo) values ('Accuvim', 'ACV')",
    "insert into Marca (nombre, codigo) values ('ALTA', 'ALT')",
    "insert into Marca (nombre, codigo) values ('Aqualabo', 'AQA')",
    "insert into Marca (nombre, codigo) values ('CDI Meters', 'CDM')",
    "insert into Marca (nombre, codigo) values ('CO2 Meter', 'CO2')",
    "insert into Marca (nombre, codigo) values ('Cross Brand', 'XBD')",
    "insert into Marca (nombre, codigo) values ('eGauge', 'EGU')",
    "insert into Marca (nombre, codigo) values ('Emporia Energy', 'EMP')",
    "insert into Marca (nombre, codigo) values ('HOBO', 'HBO')",
    "insert into Marca (nombre, codigo) values ('InTemp', 'INT')",
    "insert into Marca (nombre, codigo) values ('ION', 'ION')",
    "insert into Marca (nombre, codigo) values ('Kestrel', 'KES')",
    "insert into Marca (nombre, codigo) values ('Opsytec', 'OPY')",
    "insert into Marca (nombre, codigo) values ('Pentacom', 'PEN')",
    "insert into Marca (nombre, codigo) values ('Phionics', 'PHI')",
    "insert into Marca (nombre, codigo) values ('Premosys', 'PRM')",
    "insert into Marca (nombre, codigo) values ('Sensaphone', 'SPH')",
    "insert into Marca (nombre, codigo) values ('Stevens', 'STV')",
    "insert into Marca (nombre, codigo) values ('Ubibot', 'UBI')",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Agustín', 'Acevedo', 'Filsinger', false)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Alma', 'Lucas', 'Padilla', false)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Juana Berenice', 'Vargas', 'Abarca', false)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Diana Elizabeth', 'Lucas', 'Padilla', false)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Fernando', 'Vargas', 'Abarca', false)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Isaias', 'Velazquez', 'Cortes', true)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Juan Guillermo', 'Torres', 'Ortiz', true)",
    "insert into Usuario (nombre, paterno, materno, admin) values ('Miguel Angel', 'Hernández', '---', false)",
]
